
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-DriverAvailabilityFeature","number":50,"title":"kk - improve usability of admin Driver Availabilities","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/50"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Fixture-ReadableST","number":49,"title":"FIXTURE-make the shift table more readable","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/49"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-DayIncorrectInterpretation-Fix","number":48,"title":"BUG: Fixed Instances of Incorrect Interpretations of \"day\" field in DriverAvailability Backend.","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/48"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-Spring3-Update","number":47,"title":"Update Backend to Spring Boot 3","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/47"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-SwaggerNavbar-Feature","number":46,"title":"FEATURE: Swagger Option On Navbar","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/46"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-Dropdown-Feature-2","number":43,"title":"Dropdown Feature to Select Driver ID When Creating Shifts","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/43"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh_dropdown","number":39,"title":"dropdown feature added","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/39"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"Koray-BugFix-DriverAvailabilites","number":38,"title":"kk - driver availability bug fix","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/38"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-Dropdown-Feature","number":28,"title":"Add Dropdown Menu to Select Driver and Backup Driver","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/28"}]
