
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"Koray-BugFix-DriverAvailabilites","number":38,"title":"kk - driver availability bug fix","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/38"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-BUGFIX-nonuserAccess","number":29,"title":"fix bugs users who are not logged in cannot see the appy to rider page","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/29"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-Dropdown-Feature","number":28,"title":"Add Dropdown Menu to Select Driver and Backup Driver","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/28"},{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"RideAssignAdilFeature","number":27,"title":"ride table assign","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/27"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-RiderRole-Feature-2","number":25,"title":"Automate User 'Rider' Role Toggling","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/25"},{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-navbar","number":24,"title":"navbar fix for rider","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/24"}]
