
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"Koray-AdminTableFeature","number":54,"title":"kk - sort user table by id","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/54"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-CommitInfoFeature","number":53,"title":"Kate commit info feature","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/53"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-DAFormLabels-Fix","number":52,"title":"FEATURE: Fixed Form Labels on Driver Availability Form Page","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/52"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-DriverAvailabilityFeature","number":50,"title":"kk - improve usability of admin Driver Availabilities","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/50"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Fixture-ReadableST","number":49,"title":"June - FEATURE: Improve readability of Shift Table headers (make headers consistent)","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/49"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-Spring3-Update","number":47,"title":"Update Backend to Spring Boot 3","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/47"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh_dropdown","number":39,"title":"dropdown feature added","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/39"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"Koray-BugFix-DriverAvailabilites","number":38,"title":"kk - driver availability bug fix","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-7/pull/38"}]
